name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ArtemSerebriakov/buildozer-action@v1
        with:
          command: buildozer android debug
      - uses: actions/upload-artifact@v2
        with:
          name: my_final_apk
          path: bin/*.apk
